[env:esp32dev]
board = esp32dev
framework = arduino
platform = espressif32
lib_deps =
    ESP32 HUB75 LED MATRIX PANEL DMA Display
    adafruit/Adafruit GFX Library@^1.12.5
    WiFiManager
    ArduinoOTA
    knolleary/PubSubClient@^2.8.0
    ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=3
    ; -DNO_GFX=1
monitor_speed = 115200
